name: Update File List

on:
  push:
    branches:
      - main  # Remplacez par la branche que vous utilisez

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run C++ program
      run: |
        "D:/Winui3App/Winui3App/.github/workflows/DefineListOfPush.exe"
      shell: cmd

    - name: Commit and push changes
      run: |
        git config --global user.name 'akamesnow'
        git config --global user.email 'valentin.folliot.vf@gmail.com'
        git add D:/mon_repertoire/file_list.txt
        git commit -m "Update file list"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


